# Generated by Django 4.0.4 on 2022-05-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
        ('packages', '0002_alter_package_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.AlterField(
            model_name='package',
            name='box',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='boxes.box'),
        ),
    ]
